apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "local.labels" . | nindent 4 }}
  annotations:
    {{- include "local.serviceAnnotations" . | indent 4 }}
spec:
  type: {{ include "local.serviceType" . }}
  ports:
    - port: {{ include "local.servicePort" . }}
      targetPort: {{ include "local.serviceContainerPort" . }}
      protocol: TCP
      name: http
  selector:
    {{- include "local.selectorLabels" . | nindent 4 }}
