name: ci

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
    paths-ignore:
      - ".helm"
      - "Makefile"
      - "**.md"
  pull_request:
    branches:
      - 'main'
      - 'master'
    paths-ignore:
      - ".helm"
      - "Makefile"
      - "**.md"

env:
  docker_img_name: traviisd/kafka-producer-proxy
  
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ docker_img_name }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Docker Build
        run: docker build . --label ${{ steps.meta.outputs.labels }} -t ${{ docker_img_name }}:${{ steps.meta.outputs.tags }}
          
      - 
        name: Docker Security Scan
        uses: Azure/container-scan@v0
        with:
          image-name: ${{ docker_img_name }}:${{ steps.meta.outputs.tags }}

      -
        name: Docker Push
        if: ${{ (github.event_name != 'pull_request') && ("${GITHUB_REF##*/}" == 'master' }}
        run: docker push ${{ docker_img_name }}:${{ steps.meta.outputs.tags }}
